---
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
    timeout-minutes: 5
name: Generate pacman animation
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch: null